language: ruby

branches:
  only:
    - master

bundler_args: --without postgres development

notifications:
  email:
    - common-effort@pivotallabs.com
  webhooks:
    - http://projectmonitor-staging.pivotallabs.com/projects/50/status

rvm:
  - 1.9.3

before_script:
  - "bundle exec rake travis:setup"
  - "export DISPLAY=:99"
  - "sh -e /etc/init.d/xvfb start"

script: "bundle exec rake travis"
