language: python
python:
  - "2.7"
  - "3.4"
install:
  - sudo pip install -r requirements.txt
script: python -m projmon.test
notifications:
  webhooks: http://projmon-dev.herokuapp.com/projects/cfa-project-monitor/status
