language: ruby

bundler_args: --without postgres

notifications:
  email:
    - common-effort@pivotallabs.com

rvm:
  - 1.9.3

before_script:
  - "bundle exec rake travis:setup"
  - "export DISPLAY=:99"
  - "sh -e /etc/init.d/xvfb start"

script: "bundle exec rake travis"
